In [1]:
import pandas as pd

## Remove excess listings

In [53]:
df = pd.read_csv('data/listings.csv')
colsToKeep = ['id', 'name', 'price', 'review_scores_rating', 'review_scores_accuracy', 'review_scores_cleanliness', 'review_scores_checkin',
               'review_scores_communication', 'review_scores_location', 'review_scores_value', 'neighbourhood']
df = df[colsToKeep]
top50Listings = pd.read_csv('data/top_50.csv')
listing_ids = top50Listings['listing_id'].unique()
# len(listing_ids)
top_listings = df.loc[df['id'].isin(listing_ids)]
top_listings.to_csv('data/listings_clean.csv', index=False)

C:\Users\smart\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2728: DtypeWarning: Columns (61,62) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [2]:
df = pd.read_csv('data/listings_clean.csv')

In [4]:
df.head()

,id,name,price,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,neighbourhood
0,15440,Venice Beach Walkstreet Guesthouse,$140.00,99.0,10.0,10.0,10.0,10.0,10.0,10.0,Venice
1,54829,Beautiful Venice Beach Home Oasis,$125.00,97.0,10.0,10.0,10.0,10.0,9.0,10.0,Venice
2,69838,L.A. Lifestyle--like you live here,$97.00,96.0,10.0,9.0,10.0,10.0,10.0,10.0,Mid-Wilshire
3,76561,BECAUSE REVIEWS DON'T LIE! Go Instant Book Now!,$102.00,96.0,10.0,10.0,10.0,10.0,10.0,10.0,South LA
4,107970,2 Room Poolside Guesthouse +bikes,$90.00,95.0,10.0,10.0,10.0,10.0,10.0,10.0,Long Beach

In [6]:
df['price'] = df['price'].str.replace('$', '')
df['price'] = df['price'].astype(float)

In [7]:
df.to_csv('data/listings_clean.csv', index=False)

## Get answers

In [9]:
df = pd.read_csv('data/listings_clean.csv')
# df.drop('Unnamed: 0', inplace=True)

In [10]:
df.head()

,id,name,price,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,neighbourhood
0,15440,Venice Beach Walkstreet Guesthouse,140.0,99.0,10.0,10.0,10.0,10.0,10.0,10.0,Venice
1,54829,Beautiful Venice Beach Home Oasis,125.0,97.0,10.0,10.0,10.0,10.0,9.0,10.0,Venice
2,69838,L.A. Lifestyle--like you live here,97.0,96.0,10.0,9.0,10.0,10.0,10.0,10.0,Mid-Wilshire
3,76561,BECAUSE REVIEWS DON'T LIE! Go Instant Book Now!,102.0,96.0,10.0,10.0,10.0,10.0,10.0,10.0,South LA
4,107970,2 Room Poolside Guesthouse +bikes,90.0,95.0,10.0,10.0,10.0,10.0,10.0,10.0,Long Beach

In [7]:
summary = pd.read_csv('data/summaries2.csv', names=['id', 'summary'])

In [8]:
summary.head()

          id                                            summary
0  4014376.0  a nice place if you want to crash for a few da...
1  4014942.0  thank you katie ! this place is fantastic ! co...
2  4015029.0  we had a heart to heart one night when my pupp...
3  4015983.0  very nice place with great interior design big...
4  4015999.0  love y h probably the most especial airb b we ...

In [19]:
df.join(summary, on='id', how='left', lsuffix='l', rsuffix='r')

,idl,name,price,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,neighbourhood,idr,summary
0,15440,Venice Beach Walkstreet Guesthouse,140.0,99.0,10.0,10.0,10.0,10.0,10.0,10.0,Venice,19644151.0,building needs a little work but overall an en...
1,54829,Beautiful Venice Beach Home Oasis,125.0,97.0,10.0,10.0,10.0,10.0,9.0,10.0,Venice,NaN,NaN
2,69838,L.A. Lifestyle--like you live here,97.0,96.0,10.0,9.0,10.0,10.0,10.0,10.0,Mid-Wilshire,NaN,NaN
3,76561,BECAUSE REVIEWS DON'T LIE! Go Instant Book Now!,102.0,96.0,10.0,10.0,10.0,10.0,10.0,10.0,South LA,NaN,NaN
4,107970,2 Room Poolside Guesthouse +bikes,90.0,95.0,10.0,10.0,10.0,10.0,10.0,10.0,Long Beach,NaN,NaN
5,138211,Santa Monica/Brentwood Guest House,140.0,95.0,10.0,9.0,10.0,10.0,10.0,9.0,West Los Angeles,NaN,NaN
6,185950,Super Private Suite with View & Spa,94.0,99.0,10.0,10.0,10.0,10.0,10.0,10.0,Eagle Rock,NaN,NaN
7,260438,Private Cottage in the heart of LA,115.0,98.0,10.0,10.0,10.0,10.0,10.0,10.0,Mid-Wilshire,NaN,NaN
8,281139,Stylish Hollywood Loft with Views!,115.0,97.0,10.0,10.0,10.0,10.0,10.0,10.0,Hollywood,NaN,NaN
9,321987,Tracy's Angel room* Feel the Magic,83.0,93.0,10.0,9.0,10.0,10.0,10.0,10.0,Venice,NaN,NaN
10,394116,WALK to BEACH-10mins! FREE-BREAKFAST+Prk+WiFi-...,112.0,96.0,10.0,10.0,10.0,10.0,10.0,10.0,Venice,NaN,NaN
11,413749,Charming Silverlake/Echopark Cabin,115.0,98.0,10.0,10.0,10.0,10.0,10.0,10.0,Echo Park,NaN,NaN
12,507927,Pirates of the Caribbean Getaway,95.0,98.0,10.0,10.0,10.0,10.0,10.0,10.0,Topanga,NaN,NaN
13,528860,"Walk to Venice Beach from a Bright, Artistic Loft",159.0,95.0,10.0,10.0,10.0,10.0,10.0,9.0,Venice,NaN,NaN
14,533646,MY HOLLYWOOD SPACE RENTALS #15,65.0,94.0,10.0,10.0,10.0,10.0,9.0,10.0,Hollywood,NaN,NaN
15,561579,Tracy's StarryNight* Feel Enchanted&Romantic,108.0,94.0,10.0,9.0,10.0,10.0,10.0,10.0,Venice,NaN,NaN
16,592996,Best Beach Bed Breakfast & Bikes 1,95.0,99.0,10.0,10.0,10.0,10.0,10.0,10.0,Del Rey,NaN,NaN
17,593991,Best Beach Bed Breakfast & Bikes 2,85.0,99.0,10.0,10.0,10.0,10.0,10.0,10.0,Del Rey,NaN,NaN
18,609376,Casa de Carlos Hollywood Apartment,111.0,97.0,9.0,10.0,10.0,10.0,10.0,9.0,Hollywood Hills,NaN,NaN
19,621233,Artistic Topanga Mermaid Suite,90.0,89.0,9.0,9.0,10.0,10.0,10.0,9.0,Topanga,NaN,NaN
20,634133,Private Mid-Century Styled Guest House,110.0,98.0,10.0,10.0,10.0,10.0,10.0,10.0,Mid-Wilshire,NaN,NaN
21,847872,Adorable Arts District Guest House,79.0,86.0,9.0,9.0,10.0,10.0,10.0,9.0,North Hollywood,NaN,NaN
22,893786,Bike to the Beach from a Relaxed Apartment wit...,209.0,99.0,10.0,10.0,10.0,10.0,10.0,10.0,Venice,NaN,NaN
23,908836,Zen Garden by Universal & Hollywood,59.0,99.0,10.0,10.0,10.0,10.0,10.0,10.0,Valley Glen,NaN,NaN
24,1009059,Santa Monica Magical Organic Garden w/Free Par...,90.0,97.0,10.0,10.0,10.0,10.0,10.0,10.0,Santa Monica,NaN,NaN
25,1009472,WALK to BEACH-10mins! FREE-BREAKFAST+Prk+WiFi-RM3,92.0,96.0,10.0,10.0,10.0,10.0,10.0,9.0,Venice,NaN,NaN
26,1025161,Private Room in an Elegant French Gothic Home,99.0,97.0,10.0,10.0,10.0,10.0,10.0,10.0,Mid-Wilshire,NaN,NaN
27,1112589,cottage in the heart of Venice BCH.,110.0,98.0,10.0,10.0,10.0,10.0,10.0,10.0,Venice,NaN,NaN
28,1240919,MY HOLLYWOOD SPACE RENTALS 2,65.0,94.0,10.0,10.0,10.0,10.0,10.0,10.0,Hollywood,NaN,NaN
29,1257025,Beach side heart of santa monica/P,89.0,91.0,10.0,10.0,10.0,9.0,10.0,9.0,Santa Monica,NaN,NaN
30,1352131,MY LITTLE PARIS IN LOS ANGELES With free parking.,135.0,99.0,10.0,10.0,10.0,10.0,10.0,10.0,Downtown,NaN,NaN
31,1356645,Tracy's Loft upIn the Clouds* Feel Bliss,83.0,92.0,9.0,9.0,10.0,10.0,10.0,9.0,Venice,NaN,NaN
32,1446537,Great Private Room in Venice Beach,100.0,95.0,10.0,9.0,10.0,10.0,10.0,9.0,Venice,NaN,NaN
33,1451415,Private Room One Block to Beach,110.0,95.0,10.0,10.0,10.0,10.0,10.0,9.0,Venice,NaN,NaN
34,1506773,Tracy's TeenyTiny Castle* Feel Enchanted&Magical,73.0,89.0,10.0,9.0,10.0,10.0,10.0,8.0,Venice,NaN,NaN
35,1525686,Bike Around Town from the Sweetest Cottage in ...,175.0,97.0,10.0,10.0,10.0,10.0,10.0,9.0,Venice,NaN,NaN
36,1652433,New Cleaning Lady! ;) Hear Waves Crash! Steps2...,154.0,93.0,10.0,9.0,10.0,10.0,10.0,9.0,San Pedro,NaN,NaN
37,1906269,"Venice Bungalow, Abbot Kinney/Beach",99.0,97.0,10.0,10.0,10.0,10.0,10.0,10.0,Venice,NaN,NaN
38,1943502,BEST Downtown Loft on Airbnb!,129.0,91.0,9.0,9.0,9.0,9.0,9.0,8.0,Downtown,NaN,NaN
39,1990543,"Private 1906 Bungalow, 3 Blks from Beach",95.0,93.0,10.0,9.0,10.0,10.0,10.0,10.0,Santa Monica,NaN,NaN
40,2034041,Venice Original Private Guest House,149.0,98.0,10.0,10.0,10.0,10.0,10.0,10.0,Venice,NaN,NaN
41,2242987,West Los Angeles House with Huge Yard,70.0,99.0,10.0,10.0,10.0,10.0,10.0,10.0,Mar Vista,NaN,NaN
42,2514814,"Bright Studio, Steps to the Beach!",159.0,92.0,10.0,10.0,10.0,10.0,9.0,9.0,Venice,NaN,NaN
43,2665869,The Venice Beach Garagement,95.0,98.0,10.0,10.0,10.0,10.0,10.0,10.0,Venice,NaN,NaN
44,3259107,Super Venice Location!!,110.0,94.0,10.0,10.0,10.0,10.0,10.0,10.0,Venice,NaN,NaN
45,3884769,Venice Beach Cabana,125.0,95.0,10.0,10.0,10.0,10.0,10.0,9.0,Venice,NaN,NaN
46,4662943,Bedroom w/ shower private entrance,69.0,99.0,10.0,10.0,10.0,10.0,10.0,10.0,Mid-Wilshire,NaN,NaN
47,5683308,Urban Oasis Loft in Historical Building,145.0,97.0,10.0,10.0,10.0,10.0,10.0,10.0,Downtown,NaN,NaN
48,6031144,Cottage Guest House & Private Patio!,95.0,95.0,10.0,9.0,10.0,10.0,10.0,9.0,Hollywood,NaN,NaN
49,6438015,Venice Beach Guest Studio with Pool and Hot Tub,115.0,99.0,10.0,10.0,10.0,10.0,10.0,10.0,Venice,NaN,NaN